apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-sdk-apicurio-registry-7n6t
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sbudhwar-1-tenant/apicurio-registry-1/python-sdk-apicurio-registry-7n6t@sha256:499e678c5a9cf9e6b00f2fcd003d9313dd654d32102d5739a4906ce3edf1cd5b
        name: my-python
        resources: {}
status: {}
