apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: system-tests-apicurio-registry-agjq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: system-tests-apicurio-registry-agjq
    app.kubernetes.io/part-of: apicurio-registry-1
  name: system-tests-apicurio-registry-agjq
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-quarkus-app
    app.kubernetes.io/instance: system-tests-apicurio-registry-agjq
status:
  loadBalancer: {}
