apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-sdk-apicurio-registry-7n6t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-sdk-apicurio-registry-7n6t
    app.kubernetes.io/part-of: apicurio-registry-1
  name: python-sdk-apicurio-registry-7n6t
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-sdk-apicurio-registry-7n6t
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-sdk-apicurio-registry-7n6t
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sbudhwar-1-tenant/apicurio-registry-1/python-sdk-apicurio-registry-7n6t@sha256:201431afa19d181acff48943ebd9d410be03b3a5ac97e7ce9e300840406ac08e
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
