apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-sdk-apicurio-registry-7n6t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-sdk-apicurio-registry-7n6t
    app.kubernetes.io/part-of: apicurio-registry-1
  name: python-sdk-apicurio-registry-7n6t
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: python-sdk-apicurio-registry-7n6t
status:
  loadBalancer: {}
